server:
  port: 8081
#  servlet:
#    context-path: /ms-instructor
    
  error:
    include-details: always
    
# Oracle DB settings
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: INSTRUCTOR
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
# Dependencias


# Observabilidad (Logs  y trazas)


# Seguridad
