#DataSource setings
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: ADMISION
    password: ADMISION
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.OracleDialect

#Server
server:
  port: 8081
  servlet:
    context-path: /sc-app-ms-lissa-admision
    port: 8080
  error:
    include-message: always
    
#Version api
api.version: 1.0
    
#Discovery server
#eureka:
#  client:
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8889/eureka
    
    
# Dependencias


# Observabilidad (Logs  y trazas)


# Seguridad
